### ISSUE TITLE
Tests for elements with a tail

### ISSUE THREAD

**Issue by funkyfuture** [telota/tag-denestify.js#2]
i'd like to propose to address the diabolic property of xml/html in the tests: it's both a tree and a sequence. which results in the fact that elements can have a tailing text and it's terrorising any problem solving.

eg:

```xml
    <span style="bold">ciao ragg<del>g</del>az<ins>z</ins>i</span>
```

**Comment by suchmaske** [comment]
Has a test for this issue been implemented? @funkyfuture has a point there. Please add tests with leading and tailing text

**Comment by funkyfuture** [comment]
a test covering this was already in place. i just wasn't able to recognise it. but yeah, it's always a good idea to docuemnt why something is considered as resolved.
